### ISSUE TITLE
Streaming client error

### ISSUE THREAD

**Issue by vbmithr** [GreptimeTeam/greptimedb-client-go#83]
Sorry but I still get an error.

```golang
	tickList, _ := ticks.Ticks()
	for i := 0; i < tickList.Len(); i++ {
		tck := tickList.At(i)
		px, _ := tck.P()
		qty, _ := tck.Q()
		dpx, err := decimal.NewFromString(px)
		if err != nil {
			return err
		}
		dqty, _ := decimal.NewFromString(qty)
		series := gt.Series{}
		series.AddTag("xch", topic[len(topic)-1])
		series.SetTimestamp(time.UnixMicro(int64(tck.Lts())))
		series.AddField("rts", tck.Rts())
		series.AddField("sym", m.Key)
		series.AddField("px", dpx.InexactFloat64())
		series.AddField("qty", dqty.InexactFloat64())
		series.AddField("flag", tck.Flag())
		metric := gt.Metric{}
		metric.SetTimestampAlias("lts")
		metric.SetTimePrecision(time.Microsecond)
		metric.AddSeries(series)
		req := gt.InsertRequest{}
		req.WithTable("trade").WithMetric(metric)
		reqs := gt.InsertsRequest{}
		reqs.Insert(req)
		if err = client.Send(ctx, reqs); err != nil {
			return err
		}
		log.Debugf("%s %s %f %f %s %s", topic[len(topic)-1], m.Key, dpx.InexactFloat64(), dqty.InexactFloat64(), string(tck.Flag()), time.UnixMicro(int64(tck.Lts())))

	}
	_, err = client.CloseAndRecv(ctx)
	if err != nil {
		return err
	}
	if err = reader.CommitMessages(ctx, m); err != nil {
		return err
	}
	return nil
```

Is it possible to put all my requests into `InsertsRequest` instead of sending one by one?

Anyway I get:

```
2023-06-05T12:28:00.972+0200    ERROR   kafka2gt/main.go:200    rpc error: code = Internal desc = failed to decode Protobuf message: InsertRequest.table_name: GreptimeRequest.request: invalid string value: data is not UTF-8 encoded
```

**Comment by yuanbohan** [comment]
> Is it possible to put all my requests into InsertsRequest instead of sending one by one?

Yes, you can move the following code before your for loop:

`
reqs := gt.InsertsRequest{}
`

and move the following code after your for loop:

```
if err = client.Send(ctx, reqs); err != nil {
    return err
}
```
But it should be successful. Can you help construct your InsertRequest in hardcode way with same datatype of your original one? So I can run your snippet directly at my machine.

**Comment by vbmithr** [comment]
Yes, please check https://github.com/deepmarker/parquet2gt

**Comment by yuanbohan** [comment]
you can refer this PR to know how to solve this issue https://github.com/deepmarker/parquet2gt/pull/1

**Comment by vbmithr** [comment]
Thanks. I merged and ran and got:

```
[vb@sita ~/code/parquet2gt]% ./bin/parquet2gt data/BTC-USDT.l2.parquet
2023-06-06T09:28:21.951+0200    INFO    parquet2gt/parquet2gt.go:65     message Row {
        required int64 lts (TIMESTAMP(isAdjustedToUTC=true,unit=MICROS));
        required int64 rts (TIMESTAMP(isAdjustedToUTC=true,unit=MICROS));
        required double px;
        required double qty;
        required binary flag;
}
table: trade_34597
ready to insert 5001 series
ready to insert 5000 series
err: EOF
panic: EOF

goroutine 1 [running]:
main.doStreamInsert(0x0?, {0xc004245650?, 0xc0001c3200?}, {{0xc002c6a036, 0x3}, 0x3e8, {0xc002b67b40, 0x4, 0x4}, 0xc002b77950, ...})
        /home/vb/code/parquet2gt/parquet2gt.go:128 +0x2b7
main.streamInsert({0xc000280000, 0x4525e, 0x0?})
        /home/vb/code/parquet2gt/parquet2gt.go:157 +0x3ea
main.main()
        /home/vb/code/parquet2gt/parquet2gt.go:68 +0x45c
zsh: exit 2     ./bin/parquet2gt data/BTC-USDT.l2.parquet
```

Investigating.

**Comment by vbmithr** [comment]
Updated greptime to 466f258266ecf7b06c4281fb5971e5dee04561dd, works now. Thanks :)
